"""Columnar Transposed Alphabet Inversion for Square 1 & Square 2.

In classical British military cryptography (and Codes and Ciphers Chapter 4),
a mixed 25-letter alphabet was typically generated by:
1. Writing a primary keyword followed by the unused letters in rows of width W (e.g. 5, 6, 7, 8).
2. Reading out the columns in alphabetical order of a secondary key (or primary key).
3. Inserting the resulting 25-letter sequence into the 5x5 Polybius square using:
   - standard horizontal
   - horizontal right-to-left
   - spiral in (clockwise)
   - boustrophedon

We test all keywords from Admiralty, Cartographic, and Ordnance lexicons
across column widths W in [4, 5, 6, 7, 8, 9, 10] and reading topologies.
"""

from __future__ import annotations

import itertools
from typing import Dict, List, Set, Tuple

from projects.dagapeyeff.admiralty_sweep import ADMIRALTY_KEYWORDS_14
from projects.dagapeyeff.cartographic_corpus import (
    NIHILIST_INDICATOR_TERMS,
    ORDNANCE_SURVEY_TERMS,
)
from projects.dagapeyeff.two_square import STANDARD_ALPHABET

TARGET_SQ1 = "BDCOATXLUIGSRENHPWMYFZKQV"
TARGET_SQ2 = "WIMLTVRGCNESDYAKOZUBXFPHQ"

EXPANDED_KEYWORD_SET = sorted(list(set(
    list(ADMIRALTY_KEYWORDS_14) +
    list(ORDNANCE_SURVEY_TERMS) +
    list(NIHILIST_INDICATOR_TERMS) + [
        "HYDROGRAPHICAL", "HYDROGRAPHER", "ADMIRALTY", "NAVIGATION", "NAVIGATIONAL",
        "CARTOGRAPHY", "DRAUGHTSMAN", "TOPOGRAPHY", "TRIANGULATION", "MERIDIAN",
        "GREENWICH", "ORDNANCE", "SURVEYOR", "COMPASS", "SOUNDINGS", "COASTGUARD",
        "ROSYTH", "PORTSMOUTH", "DEVONPORT", "CHATHAM", "SCAPAFLOW", "WHITEHALL",
        "ALEXANDER", "DAGAPEYEFF", "SCHUVALOV", "PETROGRAD", "LONDON", "BRITISH",
        "ROYALNAVY", "WAROFFICE", "PATENTOFFICE", "CASSINI", "AIRY", "HOTINE",
        "BEARING", "AZIMUTH", "SEXTANT", "MAPS", "CHART", "DISPATCH", "SECRET",
    ]
)))


def make_transposed_alphabet(keyword: str, width: int = 5, key_order: str = "") -> str:
    """Generate 25-letter alphabet using columnar transposition."""
    clean_kw = "".join([c for c in keyword.upper().replace("J", "I") if c in STANDARD_ALPHABET])
    seen: Set[str] = set()
    key_chars: List[str] = []
    for c in clean_kw:
        if c not in seen:
            seen.add(c)
            key_chars.append(c)

    remainder = [c for c in STANDARD_ALPHABET if c not in seen]
    full_seq = key_chars + remainder

    # Write into grid of width W
    rows = [full_seq[i : i + width] for i in range(0, len(full_seq), width)]

    # Determine column readout order
    if key_order:
        clean_ko = "".join([c for c in key_order.upper().replace("J", "I") if c in STANDARD_ALPHABET])[:width]
        col_indices = sorted(range(len(clean_ko)), key=lambda k: clean_ko[k])
    else:
        # Standard alphabetical by first row or natural 0..width-1
        col_indices = list(range(width))

    # Read out columns
    out_chars: List[str] = []
    for c in col_indices:
        for r in range(len(rows)):
            if c < len(rows[r]):
                out_chars.append(rows[r][c])

    return "".join(out_chars[:25])


def fill_5x5(seq: str, method: str) -> str:
    """Fill 5x5 grid from 25-letter sequence."""
    if method == "horizontal_ltr":
        return seq
    elif method == "horizontal_rtl":
        grid = [["" for _ in range(5)] for _ in range(5)]
        idx = 0
        for r in range(5):
            for c in range(4, -1, -1):
                grid[r][c] = seq[idx]
                idx += 1
        return "".join("".join(row) for row in grid)
    elif method == "vertical_ttb":
        grid = [["" for _ in range(5)] for _ in range(5)]
        idx = 0
        for c in range(5):
            for r in range(5):
                grid[r][c] = seq[idx]
                idx += 1
        return "".join("".join(row) for row in grid)
    elif method == "spiral_in":
        grid = [["" for _ in range(5)] for _ in range(5)]
        top, bottom, left, right = 0, 4, 0, 4
        idx = 0
        while top <= bottom and left <= right and idx < 25:
            for c in range(left, right + 1):
                grid[top][c] = seq[idx]
                idx += 1
            top += 1
            for r in range(top, bottom + 1):
                grid[r][right] = seq[idx]
                idx += 1
            right -= 1
            if top <= bottom:
                for c in range(right, left - 1, -1):
                    grid[bottom][c] = seq[idx]
                    idx += 1
                bottom -= 1
            if left <= right:
                for r in range(bottom, top - 1, -1):
                    grid[r][left] = seq[idx]
                    idx += 1
                left += 1
        return "".join("".join(row) for row in grid)
    return seq


def main() -> None:
    print("=" * 80)
    print("COLUMNAR TRANSPOSED ALPHABET INVERSION")
    print(f"Testing {len(EXPANDED_KEYWORD_SET)} Keywords across Widths [4..8] and Topologies")
    print("=" * 80)

    best_sq1 = []
    best_sq2 = []

    widths = [4, 5, 6, 7, 8]
    methods = ["horizontal_ltr", "horizontal_rtl", "vertical_ttb", "spiral_in"]

    for kw in EXPANDED_KEYWORD_SET:
        for w in widths:
            for ko in ["", kw]:
                try:
                    alpha = make_transposed_alphabet(kw, width=w, key_order=ko)
                    for m in methods:
                        grid = fill_5x5(alpha, m)
                        match1 = sum(1 for a, b in zip(grid, TARGET_SQ1) if a == b)
                        match2 = sum(1 for a, b in zip(grid, TARGET_SQ2) if a == b)

                        best_sq1.append((match1, kw, w, ko[:6], m, grid))
                        best_sq2.append((match2, kw, w, ko[:6], m, grid))
                except Exception:
                    continue

    best_sq1.sort(key=lambda x: x[0], reverse=True)
    best_sq2.sort(key=lambda x: x[0], reverse=True)

    print("\nTop 10 Matches for Square 1 (Target: BDCOATXLUIGSRENHPWMYFZKQV):")
    for i, (m, kw, w, ko, meth, g) in enumerate(best_sq1[:10], 1):
        print(f"{i:2d}. [{m:2d}/25 exact] Kw: {kw:16s} W={w} KeyOrd={ko:6s} Method: {meth:14s} Grid: {g}")

    print("\nTop 10 Matches for Square 2 (Target: WIMLTVRGCNESDYAKOZUBXFPHQ):")
    for i, (m, kw, w, ko, meth, g) in enumerate(best_sq2[:10], 1):
        print(f"{i:2d}. [{m:2d}/25 exact] Kw: {kw:16s} W={w} KeyOrd={ko:6s} Method: {meth:14s} Grid: {g}")


if __name__ == "__main__":
    main()
